language: php

dist: bionic

addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - rabbitmq
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - DB=mysql
  - DB=sqlite

install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update
  - sudo apt-get install -y librabbitmq-dev
  - echo | pecl install -f amqp-1.9.4
  - sudo rabbitmq-plugins enable rabbitmq_management

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - rm -rf vendor/phpservicebus/core
  - travis_retry composer install --no-interaction --prefer-source
  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE IF NOT EXISTS servicebus;'; fi

script:
  - if [[ $TRAVIS_PHP_VERSION != '7.1' || $DB != 'mysql' ]]; then bin/phpspec run --config phpspec.$DB.yml.dist; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.1' && $DB == 'mysql' ]]; then bin/phpspec run --config phpspec.mysql.yml.ci; fi
  - bin/phpunit -c phpunit.$DB.xml.dist

after_script:
  - if [[ $TRAVIS_PHP_VERSION == '7.1' && $DB == 'mysql' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

cache:
  directories:
    - $HOME/.composer/cache
