language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=mysql
  - DB=sqlite

sudo: false

services:
  - rabbitmq

install:
  - echo | pecl install -f amqp-1.7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - rm -rf vendor/phpservicebus/core
  - travis_retry composer install --no-interaction --prefer-source
  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE IF NOT EXISTS servicebus;'; fi

script:
  - if [[ $TRAVIS_PHP_VERSION != '5.6' || $DB != 'mysql' ]]; then bin/phpspec run --config phpspec.$DB.yml.dist; fi
  - if [[ $TRAVIS_PHP_VERSION == '5.6' && $DB == 'mysql' ]]; then bin/phpspec run --config phpspec.mysql.yml.ci; fi
  - bin/phpunit -c phpunit.$DB.xml.dist

after_script:
  - if [[ $TRAVIS_PHP_VERSION == '5.6' && $DB == 'mysql' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

cache:
  directories:
    - $HOME/.composer/cache
